# Generated by Django 5.0.6 on 2024-06-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTossi', '0002_recetas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empanada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('price', models.IntegerField(max_length=30)),
                ('ingredients', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('price', models.IntegerField(max_length=30)),
                ('ingredients', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Postre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('price', models.IntegerField(max_length=30)),
                ('ingredients', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Recetas',
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
