# Generated by Django 5.0.6 on 2024-06-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTossi', '0003_empanada_pizza_postre_delete_recetas_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empanada',
            name='ingredients',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='ingredients',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='postre',
            name='ingredients',
            field=models.CharField(max_length=200),
        ),
    ]
