# Generated by Django 5.0.6 on 2024-06-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTossi', '0004_alter_empanada_ingredients_alter_pizza_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AlterField(
            model_name='empanada',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postre',
            name='price',
            field=models.IntegerField(),
        ),
    ]
