# Generated by Django 5.0.6 on 2024-06-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTossi', '0005_sugerencia_delete_menu_alter_empanada_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sugerencia',
        ),
    ]
