# Generated by Django 5.0.6 on 2024-06-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTossi', '0007_postre_img_postre_stock_postre_vegetarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='empanada',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='empanada',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empanada',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pizza',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
