# Generated by Django 5.0.6 on 2024-06-16 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTossi', '0008_empanada_img_empanada_stock_empanada_vegetarian_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='img',
            new_name='image',
        ),
    ]
