# Generated by Django 5.0.6 on 2024-06-22 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTossi', '0009_rename_img_pizza_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='image',
            new_name='img',
        ),
    ]
